### ISSUE TITLE
Composer error, Laravel 9

### ISSUE THREAD

**Issue by gabyyro** [datacreativa/laravel-presentable#6]
Hello, I got this error while installing, also tried with specifying 1.1.0 version.

` Problem 1
    - Root composer.json requires datacreativa/laravel-presentable ^1.2 -> satisfiable by datacreativa/laravel-presentable[v1.2.0].
    - datacreativa/laravel-presentable v1.2.0 requires illuminate/support ^10.0 -> found illuminate/support[v10.0.0, ..., v10.3.3] but these were not loaded, likely because it conflicts with another require.
`

**Comment by ErickZH** [comment]
Hello @gabyyro  I check this issue

**Comment by basherdesigns** [comment]
I have this similar issue when going from Laravel 9.52.4 to 9.52.5:
```
Problem 1
    - Root composer.json requires datacreativa/laravel-presentable ^0.0.2, found datacreativa/laravel-presentable[dev-master, v1.0.0, v1.1.0, v1.2.0] but these do not match your constraint and are therefore not installable. Make sure you either fix the constraint or avoid updating this package to keep the one present in the lock file (datacreativa/laravel-presentable[v0.0.2]).

**Comment by jhjvandenbroek** [comment]
Problem is all versions have the same composer.json with require "illuminate/support": "^10.0"

Because of this installing it on Laravel 9 or earlier won't work
